version: '2'

services:
   db:
     build: db
     ports:
       - "3306:3306"
     volumes:
       - ./db_data:/var/lib/mysql
       - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: origin
       MYSQL_USER: user1
       MYSQL_PASSWORD: root
